### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by kapstok** [luluco250/RegexTester#1]
Hey,

I wanted to give your project a try on my Linux machine. Unfortunately, I don't know how to build this project myself.
Could you add instructions to `README.md` on how to compile the project?

**Comment by kapstok** [comment]
Already found out how to compile:

```bash
meson compile
cd compile
ninja
```

**Comment by luluco250** [comment]
Hey. sorry I didn't reply to you, I didn't even remember this project lol.

But yeah Meson is generally pretty simple to use.

I normally use:
```sh
meson build
cd build
meson compile
```

I guess I can add instructions to the README.md.
